### PR TITLE
Delete obsolete charts directory

### PR DESCRIPTION
**Pull request by stackedsax**
@shashiranjan84 Isn't this directory rendered obsolete from the work you did to put cassandra and postgres into the requirements.yaml?  

Assuming so, so I figured I'd just clean this up a bit.  Plus, I just keep getting confused about which template and values file I'm looking at...

### CODE REVIEW

**Comment by shashiranjan84** [comment]
Yes, I am aware of this. I had this problem during packaging and wanted to research about it later

image

Any idea why this failing?

**Comment by stackedsax** [comment]
I am in the exact same hell.  I have zero idea why this is happening.  

It is interesting, though, that if you unpack those tgz's into charts, everything is fine.

**Comment by stackedsax** [comment]
Figured it out!  It's an errant *.tgz in the .helmignore file.  Removing it makes things workout just fine.

**Comment by stackedsax** [comment]
eh, I made a hash of the rebase.  Let me fix in the morning when I'm not so blurry-eyed.

**Comment by shashiranjan84** [comment]
I figured out too while working on official chart for Kubeapps hub https://github.com/shashiranjan84/charts/commits/master.

Thanks for PR.

**Comment by stackedsax** [comment]
@shashiranjan84 Good to know!

A couple q's:

- Do you still want to merge any of these PR's?
- Should we move to doing development in that official repo from now on?
- Should we take this chart down and put a README directing people to where the chart will actually live?
- And do you want to put your work in incubator/ rather than stable/ over there?  I feel like that's where this wip work should go until it's a bit more baked.

**Comment by shashiranjan84** [comment]
> Do you still want to merge any of these PR's?

Yes, we will maintain this repo and add Kong-EE options

> Should we move to doing development in that official repo from now on?
> Should we take this chart down and put a README directing people to where the chart will actually live?

For now both will be maintained

> And do you want to put your work in incubator/ rather than stable/ over there? I feel like that's where this wip work should go until it's a bit more baked.

No, will make sure we meet stable criteria before sending PR

**Pull request merged**
